title: Web Project
description: 'Explore the world of creativity '
template:
  repo: web-project-template
  name: web-project
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
